### ISSUE TITLE
@here bot

### ISSUE THREAD

**Issue by jonasgeiler** [C0D4-101/devrant-bots#4]
Just confirming that I've created the @here bot

See #5

**Comment by kescherCode** [comment]
I know this because I've chatted with him as he talked about making a bot that tags everyone in a discussion as is the case when someone mentions [at]here in a Discord chat. I'm sure that in doubt, Skayo can provide further proof that the he owns his bot.

**Comment by jonasgeiler** [comment]
> I know this because I've chatted with him as he talked about making a bot that tags everyone in a discussion as is the case when someone mentions [at]here in a Discord chat. I'm sure that in doubt, Skayo can provide further proof that the he owns his bot.

I've updated it's profile description I'm sure that's enough proof xD
